#!/bin/sh
# Generate a minimal initramfs-friendly manifest.env from a manifest.json.
# Requires: jq
set -eu

IN=${1:-manifest.json}
OUT=${2:-manifest.env}

command -v jq >/dev/null 2>&1 || {
  echo "jq required" >&2
  exit 2
}

STACK_ORDER=$(jq -r '[.stack[].type] | join(",")' "$IN")
DATA_IMAGE=$(jq -r '.images.data.path' "$IN")
INTEGRITY_META_IMAGE=$(jq -r '.images.integrity_meta.path // empty' "$IN")

CRYPT_MODE=$(jq -r '.crypt.mode // ""' "$IN")
CRYPT_CIPHER=$(jq -r '.crypt.cipher // ""' "$IN")
CRYPT_KEY_BYTES=$(jq -r '.crypt.key_bytes // ""' "$IN")
CRYPT_SECTOR_SIZE=$(jq -r '.crypt.sector_size // ""' "$IN")
CRYPT_IV_OFFSET=$(jq -r '.crypt.iv_offset // ""' "$IN")

INTEGRITY_TAG_SIZE=$(jq -r '.integrity.tag_size // ""' "$IN")
INTEGRITY_BLOCK_SIZE=$(jq -r '.integrity.block_size // ""' "$IN")
INTEGRITY_MODE=$(jq -r '.integrity.mode // ""' "$IN")
INTEGRITY_BUFFER_SECTORS=$(jq -r '.integrity.buffer_sectors // ""' "$IN")

ROOTFS_MOUNTPOINT=$(jq -r '.rootfs.mountpoint // ""' "$IN")
ROOTFS_FSTYPE=$(jq -r '.rootfs.fstype // ""' "$IN")
ROOTFS_OPTS_BOOTSTRAP=$(jq -r '.rootfs.opts_bootstrap // ""' "$IN")
ROOTFS_OPTS_SEALED=$(jq -r '.rootfs.opts_sealed // ""' "$IN")

# Write POSIX shell assignments.
# shellcheck disable=SC2129
{
  echo "# Autogenerated from $IN"
  echo "STACK_ORDER=$STACK_ORDER"

  # Image paths are stored for reference (activation needs real block devices)
  echo "DATA_IMAGE=$DATA_IMAGE"
  [ -n "$INTEGRITY_META_IMAGE" ] && echo "INTEGRITY_META_IMAGE=$INTEGRITY_META_IMAGE"

  # dm-crypt params
  [ -n "$CRYPT_MODE" ] && echo "CRYPT_MODE=$CRYPT_MODE"
  [ -n "$CRYPT_CIPHER" ] && echo "CRYPT_CIPHER=\"$CRYPT_CIPHER\""
  [ -n "$CRYPT_KEY_BYTES" ] && echo "CRYPT_KEY_BYTES=$CRYPT_KEY_BYTES"
  [ -n "$CRYPT_SECTOR_SIZE" ] && echo "CRYPT_SECTOR_SIZE=$CRYPT_SECTOR_SIZE"
  [ -n "$CRYPT_IV_OFFSET" ] && echo "CRYPT_IV_OFFSET=$CRYPT_IV_OFFSET"

  # dm-integrity params
  [ -n "$INTEGRITY_TAG_SIZE" ] && echo "INTEGRITY_TAG_SIZE=$INTEGRITY_TAG_SIZE"
  [ -n "$INTEGRITY_BLOCK_SIZE" ] && echo "INTEGRITY_BLOCK_SIZE=$INTEGRITY_BLOCK_SIZE"
  [ -n "$INTEGRITY_MODE" ] && echo "INTEGRITY_MODE=$INTEGRITY_MODE"
  [ -n "$INTEGRITY_BUFFER_SECTORS" ] && echo "INTEGRITY_BUFFER_SECTORS=$INTEGRITY_BUFFER_SECTORS"

  # rootfs hints
  [ -n "$ROOTFS_MOUNTPOINT" ] && echo "ROOTFS_MOUNTPOINT=\"$ROOTFS_MOUNTPOINT\""
  [ -n "$ROOTFS_FSTYPE" ] && echo "ROOTFS_FSTYPE=\"$ROOTFS_FSTYPE\""
  [ -n "$ROOTFS_OPTS_BOOTSTRAP" ] && echo "ROOTFS_OPTS_BOOTSTRAP=\"$ROOTFS_OPTS_BOOTSTRAP\""
  [ -n "$ROOTFS_OPTS_SEALED" ] && echo "ROOTFS_OPTS_SEALED=\"$ROOTFS_OPTS_SEALED\""

  echo
  echo "# ---- device-mapper-tools (DMT_) variables ----"
  echo "# Provide these at runtime in initramfs (not stored in manifest):"
  echo "#   DMT_MODE=apply|dry-run"
  echo "#   DMT_PHASE=bootstrap|sealed"
  echo "#   DMT_DATA_BDEV=/dev/<blockdev>"
  echo "#   DMT_INTEGRITY_META_BDEV=/dev/<blockdev>   (if stack includes dm-integrity)"
  echo "#   DMT_CRYPT_KEY_HEX=<hex> or DMT_CRYPT_KEY_BIN=/path/key.bin"
} > "$OUT"

echo "$OUT"
