#!/bin/sh
# Generate a minimal initramfs-friendly manifest.env from a manifest.json.
# Requires: jq
set -eu

IN=${1:-manifest.json}
OUT=${2:-manifest.env}

command -v jq >/dev/null 2>&1 || {
  echo "jq required" >&2
  exit 2
}

STACK_ORDER=$(jq -r '[.stack[].type] | join(",")' "$IN")
DATA_IMAGE=$(jq -r '.images.data.path' "$IN")
INTEGRITY_META_IMAGE=$(jq -r '.images.integrity_meta.path // empty' "$IN")

CRYPT_MODE=$(jq -r '.crypt.mode // ""' "$IN")
CRYPT_CIPHER=$(jq -r '.crypt.cipher // ""' "$IN")
CRYPT_KEY_BYTES=$(jq -r '.crypt.key_bytes // ""' "$IN")
CRYPT_SECTOR_SIZE=$(jq -r '.crypt.sector_size // ""' "$IN")
CRYPT_IV_OFFSET=$(jq -r '.crypt.iv_offset // ""' "$IN")

INTEGRITY_TAG_SIZE=$(jq -r '.integrity.tag_size // ""' "$IN")
INTEGRITY_BLOCK_SIZE=$(jq -r '.integrity.block_size // ""' "$IN")
INTEGRITY_MODE=$(jq -r '.integrity.mode // ""' "$IN")
INTEGRITY_BUFFER_SECTORS=$(jq -r '.integrity.buffer_sectors // ""' "$IN")

# Write POSIX shell assignments.
# shellcheck disable=SC2129
{
  echo "# Autogenerated from $IN"
  echo "STACK_ORDER=$STACK_ORDER"
  echo "DATA_IMAGE=$DATA_IMAGE"
  [ -n "$INTEGRITY_META_IMAGE" ] && echo "INTEGRITY_META_IMAGE=$INTEGRITY_META_IMAGE"

  [ -n "$CRYPT_MODE" ] && echo "CRYPT_MODE=$CRYPT_MODE"
  [ -n "$CRYPT_CIPHER" ] && echo "CRYPT_CIPHER=\"$CRYPT_CIPHER\""
  [ -n "$CRYPT_KEY_BYTES" ] && echo "CRYPT_KEY_BYTES=$CRYPT_KEY_BYTES"
  [ -n "$CRYPT_SECTOR_SIZE" ] && echo "CRYPT_SECTOR_SIZE=$CRYPT_SECTOR_SIZE"
  [ -n "$CRYPT_IV_OFFSET" ] && echo "CRYPT_IV_OFFSET=$CRYPT_IV_OFFSET"

  [ -n "$INTEGRITY_TAG_SIZE" ] && echo "INTEGRITY_TAG_SIZE=$INTEGRITY_TAG_SIZE"
  [ -n "$INTEGRITY_BLOCK_SIZE" ] && echo "INTEGRITY_BLOCK_SIZE=$INTEGRITY_BLOCK_SIZE"
  [ -n "$INTEGRITY_MODE" ] && echo "INTEGRITY_MODE=$INTEGRITY_MODE"
  [ -n "$INTEGRITY_BUFFER_SECTORS" ] && echo "INTEGRITY_BUFFER_SECTORS=$INTEGRITY_BUFFER_SECTORS"
} > "$OUT"

echo "$OUT"
